<a href="https://colab.research.google.com/github/shaikfardin/-ML2021/blob/main/ai%26ds_weak_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [ ]:
x=np.zeros((5),dtype=np.int16)
y=np.zeros([2,3],dtype=np.int16)
print(x)
print(y)

[0 0 0 0 0]
[[0 0 0]
 [0 0 0]]


In [ ]:
x=np.ones((5),dtype=np.int16)
y=np.ones((2,2),dtype=np.int16)
print(x)
print(y)

[1 1 1 1 1]
[[1 1]
 [1 1]]


In [ ]:
 x=np.random.choice([1,2,3],size=(2,3))
 print(x)

[[2 1 3]
 [3 1 2]]


In [ ]:
x=np.random.randint(50,size=(2,4))
x

array([[43,  5, 20,  2],
       [14, 48, 11, 29]])

In [ ]:
x=np.matrix([[1,2,3],[12,3]])
x

/usr/local/lib/python3.7/dist-packages/numpy/matrixlib/defmatrix.py:145: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = N.array(data, dtype=dtype, copy=copy)


matrix([[list([1, 2, 3]), list([12, 3])]], dtype=object)

In [ ]:
x=np.arange(1,10,2)
x

array([1, 3, 5, 7, 9])